### ISSUE TITLE
CUDA out of memory during preprocessing

### ISSUE THREAD

**Issue by joetorsney** [lesterphillip/SVCC23_FastSVC#7]
I'm trying to recreate the experiment in the original FastSVC paper using the NUS48E dataset. Unfortunately the GPU is running out of memory during ppg extraction in stage 1 of preprocessing. I've tried reducing both `batch_size` and `batch_length` in `fastsvc16kHz.yml` to try an alleviate the memory problems. I also reduced the size of the train set by ~20%, and made the source wavs mono and 16khz in case there was some funny garbage collection going on. Here's the full log

```
# harana-preprocess --config conf/fastsvc16kHz.yaml --scp dump/train_full/raw/wav.2.scp --dumpdir dump/train_full/raw/dump.2 --device cuda --spk_emb_path dump/train_full/embs/spk_embs.h5 --f0_path conf/f0.yml 
# Started at Tue  4 Apr 16:00:52 BST 2023
#
2023-04-04 16:00:57,077 (conformer_encoder:117) INFO: Encoder input layer type: conv2d
2023-04-04 16:00:57,086 (subsampling:107) INFO: Encoder does not do down-sample on mel-spectrogram.

  0%|          | 0/12 [00:00<?, ?it/s]2023-04-04 16:01:01,420 (preprocess:180) INFO: processing 13
2023-04-04 16:01:01,429 (preprocess:213) WARNING: cannot find f0 information of 13, using default values
2023-04-04 16:01:01,430 (preprocess:225) INFO: input_audio (3796152,)
/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/librosa/core/convert.py:1350: RuntimeWarning: divide by zero encountered in log10
  + 2 * np.log10(f_sq)
/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/functional.py:606: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at  ../aten/src/ATen/native/SpectralOps.cpp:803.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/ppg/stft.py:111: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  olens = (ilens - self.win_length) // self.hop_length + 1

  0%|          | 0/12 [02:19<?, ?it/s]
<_io.BufferedReader name='/export/catch1/student-projects/darwin2223-voice-conversion/data/nus48/MPOL/sing/19.wav'>, 2
2
Traceback (most recent call last):
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/bin/harana-preprocess", line 33, in <module>
    sys.exit(load_entry_point('harana', 'console_scripts', 'harana-preprocess')())
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/bin/preprocess.py", line 243, in main
    raw_ppg = ppg_extract(audio16k, args.device, ppg_extractor)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/bin/preprocess.py", line 89, in ppg_extract
    bnf = model(wav_tensor, wav_length)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/ppg/build_ppg_model.py", line 47, in forward
    encoder_out, encoder_out_lens, _ = self.encoder(feats, feats_lengths)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/ppg/encoder/conformer_encoder.py", line 242, in forward
    xs_pad, masks = self.encoders(xs_pad, masks)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/ppg/encoder/repeat.py", line 18, in forward
    args = m(*args)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/ppg/encoder/encoder_layer.py", line 114, in forward
    x_att = self.self_attn(x_q, x, x, pos_emb, mask)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/ppg/encoder/attention.py", line 179, in forward
    scores = (matrix_ac + matrix_bd) / math.sqrt(
RuntimeError: CUDA out of memory. Tried to allocate 8.39 GiB (GPU 0; 47.46 GiB total capacity; 25.35 GiB already allocated; 1.64 GiB free; 25.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
# Accounting: time=149 threads=1
# Ended (code 1) at Tue  4 Apr 16:03:21 BST 2023, elapsed time 149 seconds
```

Any help would be appreciated.
Thanks

**Comment by lesterphillip** [comment]
Thanks! I'm assuming you're using the entire 2-3min per utterance NUS48E, right? Since the PPG extractor is based on a Conformer, it's going to be heavy on the GPU if you use CUDA during extraction. So what I did to resolve this was either:

1. Cut the NUS48E to smaller chunks of 10s
2. Use just the CPU during preprocessing (you can change it in the run.sh file with the device_feat_extract variable). A thing I also did was add a line to specify to use cuda for train/dev (VCTK) and CPU for eval (NUS48E) if you want to preprocess all of them at the same time.

An unrelated comment, but from what I saw in your logs, you might want to set the min and max F0 for each speaker to get better results. I can share the F0 values for NUS48E around tomorrow.

Hope this helps!

**Comment by joetorsney** [comment]
Ahh I see. That seems to have worked, thank you very much! You're right I'm using the default F0 values, do you have those?

**Comment by lesterphillip** [comment]
Here it is, along with VCTK. I calculated the ones for NUS48E, but the VCTK ones are from my colleague [here.](https://github.com/chomeyama/HN-UnifiedSourceFilterGAN/blob/master/egs/vctk/data/spk_info.yaml)

If you're using a different dataset you can calculate the F0 range using [these instructions.](https://github.com/k2kobayashi/sprocket/blob/master/docs/vc_example.md#3-modify-f0-search-range)

```

p225:
  minf0: 130
  maxf0: 260
  pow_th: -20
p226:
  minf0: 80
  maxf0: 180
  pow_th: -20
p227:
  minf0: 80
  maxf0: 190
  pow_th: -20
p228:
  minf0: 120
  maxf0: 300
  pow_th: -20
p229:
  minf0: 140
  maxf0: 230
  pow_th: -20
p230:
  minf0: 140
  maxf0: 260
  pow_th: -20
p231:
  minf0: 110
  maxf0: 280
  pow_th: -20
p232:
  minf0: 70
  maxf0: 180
  pow_th: -20
p233:
  minf0: 150
  maxf0: 290
  pow_th: -20
p234:
  minf0: 130
  maxf0: 270
  pow_th: -20
p236:
  minf0: 170
  maxf0: 330
  pow_th: -20
p237:
  minf0: 60
  maxf0: 120
  pow_th: -20
p238:
  minf0: 140
  maxf0: 320
  pow_th: -20
p239:
  minf0: 140
  maxf0: 270
  pow_th: -20
p240:
  minf0: 150
  maxf0: 330
  pow_th: -20
p241:
  minf0: 85
  maxf0: 170
  pow_th: -20
p243:
  minf0: 80
  maxf0: 180
  pow_th: -20
p244:
  minf0: 150
  maxf0: 320
  pow_th: -20
p245:
  minf0: 70
  maxf0: 130
  pow_th: -20
p246:
  minf0: 70
  maxf0: 140
  pow_th: -20
p247:
  minf0: 90
  maxf0: 200
  pow_th: -20
p248:
  minf0: 130
  maxf0: 390
  pow_th: -20
p249:
  minf0: 130
  maxf0: 240
  pow_th: -20
p250:
  minf0: 110
  maxf0: 380
  pow_th: -20
p251:
  minf0: 80
  maxf0: 170
  pow_th: -20
p252:
  minf0: 80
  maxf0: 160
  pow_th: -20
p253:
  minf0: 160
  maxf0: 310
  pow_th: -20
p254:
  minf0: 55
  maxf0: 120
  pow_th: -20
p255:
  minf0: 95
  maxf0: 210
  pow_th: -20
p256:
  minf0: 60
  maxf0: 130
  pow_th: -20
p257:
  minf0: 150
  maxf0: 300
  pow_th: -20
p258:
  minf0: 90
  maxf0: 170
  pow_th: -20
p259:
  minf0: 80
  maxf0: 200
  pow_th: -20
p260:
  minf0: 70
  maxf0: 170
  pow_th: -20
p261:
  minf0: 140
  maxf0: 360
  pow_th: -20
p262:
  minf0: 120
  maxf0: 250
  pow_th: -20
p263:
  minf0: 70
  maxf0: 160
  pow_th: -20
p264:
  minf0: 150
  maxf0: 250
  pow_th: -20
p265:
  minf0: 130
  maxf0: 290
  pow_th: -20
p266:
  minf0: 100
  maxf0: 300
  pow_th: -20
p267:
  minf0: 130
  maxf0: 270
  pow_th: -20
p268:
  minf0: 130
  maxf0: 300
  pow_th: -20
p269:
  minf0: 150
  maxf0: 260
  pow_th: -20
p270:
  minf0: 75
  maxf0: 150
  pow_th: -20
p271:
  minf0: 90
  maxf0: 160
  pow_th: -20
p272:
  minf0: 80
  maxf0: 180
  pow_th: -20
p273:
  minf0: 100
  maxf0: 220
  pow_th: -20
p274:
  minf0: 75
  maxf0: 150
  pow_th: -20
p275:
  minf0: 80
  maxf0: 160
  pow_th: -20
p276:
  minf0: 170
  maxf0: 340
  pow_th: -20
p277:
  minf0: 160
  maxf0: 260
  pow_th: -20
p278:
  minf0: 80
  maxf0: 170
  pow_th: -20
p279:
  minf0: 80
  maxf0: 200
  pow_th: -20
p280:
  minf0: 140
  maxf0: 280
  pow_th: -20
p281:
  minf0: 70
  maxf0: 140
  pow_th: -20
p282:
  minf0: 150
  maxf0: 250
  pow_th: -20
p283:
  minf0: 160
  maxf0: 280
  pow_th: -20
p284:
  minf0: 60
  maxf0: 170
  pow_th: -20
p285:
  minf0: 80
  maxf0: 180
  pow_th: -20
p286:
  minf0: 90
  maxf0: 210
  pow_th: -20
p287:
  minf0: 65
  maxf0: 140
  pow_th: -20
p288:
  minf0: 130
  maxf0: 300
  pow_th: -20
p292:
  minf0: 70
  maxf0: 170
  pow_th: -20
p293:
  minf0: 130
  maxf0: 260
  pow_th: -20
p294:
  minf0: 120
  maxf0: 260
  pow_th: -20
p295:
  minf0: 140
  maxf0: 260
  pow_th: -20
p297:
  minf0: 120
  maxf0: 300
  pow_th: -20
p298:
  minf0: 80
  maxf0: 190
  pow_th: -20
p299:
  minf0: 110
  maxf0: 270
  pow_th: -20
p300:
  minf0: 130
  maxf0: 270
  pow_th: -20
p301:
  minf0: 120
  maxf0: 250
  pow_th: -20
p302:
  minf0: 90
  maxf0: 180
  pow_th: -20
p303:
  minf0: 160
  maxf0: 300
  pow_th: -20
p304:
  minf0: 65
  maxf0: 160
  pow_th: -20
p305:
  minf0: 160
  maxf0: 330
  pow_th: -20
p306:
  minf0: 130
  maxf0: 260
  pow_th: -20
p307:
  minf0: 160
  maxf0: 400
  pow_th: -20
p308:
  minf0: 140
  maxf0: 280
  pow_th: -20
p310:
  minf0: 170
  maxf0: 350
  pow_th: -20
p311:
  minf0: 75
  maxf0: 160
  pow_th: -20
p312:
  minf0: 130
  maxf0: 280
  pow_th: -20
p313:
  minf0: 120
  maxf0: 260
  pow_th: -20
p314:
  minf0: 120
  maxf0: 270
  pow_th: -20
p315:
  minf0: 90
  maxf0: 190
  pow_th: -20
p316:
  minf0: 65
  maxf0: 140
  pow_th: -20
p317:
  minf0: 175
  maxf0: 360
  pow_th: -20
p318:
  minf0: 110
  maxf0: 290
  pow_th: -20
p323:
  minf0: 130
  maxf0: 390
  pow_th: -20
p326:
  minf0: 50
  maxf0: 110
  pow_th: -20
p329:
  minf0: 150
  maxf0: 280
  pow_th: -20
p330:
  minf0: 140
  maxf0: 270
  pow_th: -20
p333:
  minf0: 120
  maxf0: 270
  pow_th: -20
p334:
  minf0: 65
  maxf0: 140
  pow_th: -20
p335:
  minf0: 130
  maxf0: 310
  pow_th: -20
p336:
  minf0: 130
  maxf0: 310
  pow_th: -20
p339:
  minf0: 120
  maxf0: 310
  pow_th: -20
p340:
  minf0: 170
  maxf0: 270
  pow_th: -20
p341:
  minf0: 130
  maxf0: 280
  pow_th: -20
p343:
  minf0: 110
  maxf0: 240
  pow_th: -20
p345:
  minf0: 70
  maxf0: 140
  pow_th: -20
p347:
  minf0: 60
  maxf0: 130
  pow_th: -20
p351:
  minf0: 170
  maxf0: 280
  pow_th: -20
p360:
  minf0: 70
  maxf0: 160
  pow_th: -20
p361:
  minf0: 120
  maxf0: 290
  pow_th: -20
p362:
  minf0: 130
  maxf0: 300
  pow_th: -20
p363:
  minf0: 70
  maxf0: 180
  pow_th: -20
p364:
  minf0: 65
  maxf0: 145
  pow_th: -20
p374:
  minf0: 70
  maxf0: 190
  pow_th: -20
p376:
  minf0: 70
  maxf0: 170
  pow_th: -20
s5:
  minf0: 140
  maxf0: 340
  pow_th: -20
ADIZ:
  maxf0: 490
  minf0: 150
JLEE:
  maxf0: 340
  minf0: 90
JTAN:
  maxf0: 300
  minf0: 50
KENN:
  maxf0: 340
  minf0: 90
MCUR:
  maxf0: 500
  minf0: 140
MPOL:
  maxf0: 510
  minf0: 140
MPUR:
  maxf0: 510
  minf0: 140
NJAT:
  maxf0: 510
  minf0: 140
PMAR:
  maxf0: 510
  minf0: 140
SAMF:
  maxf0: 290
  minf0: 90
VKOW:
  maxf0: 340
  minf0: 50
ZHIY:
  maxf0: 340
  minf0: 90
```

**Comment by joetorsney** [comment]
That's fantastic. Thanks for your help!
