### ISSUE TITLE
CUDA illegal memory access error on evaluation

### ISSUE THREAD

**Issue by joetorsney** [lesterphillip/SVCC23_FastSVC#8]
I'm trying to train FastSVC on a single speaker, and using the same speaker in evaluation to test how well the model can reconstruct their voice. After 5000 steps, during the first evaluation, the training terminates with a CUDA illegal memory access violation. I've attached the error at the end but I'm not sure how helpful it is.

Things I've tried
- Ensuring that files listed in `data/evaluation_samples/wav.scp` actually exist and have the format `SPEAKERID_filename /absolute/file/path.wav`
- Set `convert_to_speakers: ["SPEAKERID"]` in `conf/fastsvc16khz.yml` (?)
- Deleting `dump` and rerunning stages 1-3.

If I set `eval_interval_steps` to be bigger than `train_max_steps`, do you think this error will prevent me from running stage 5?

```
[eval]:   0%|          | 0/6 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/bin/train_fastsvc.py", line 814, in main
    trainer.run()
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/bin/train_fastsvc.py", line 95, in run
    self._train_epoch()
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/bin/train_fastsvc.py", line 250, in _train_epoch
    self._check_eval_interval()
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/bin/train_fastsvc.py", line 419, in _check_eval_interval
    self._eval_epoch()
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/bin/train_fastsvc.py", line 325, in _eval_epoch
    self._eval_step(batch)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/bin/train_fastsvc.py", line 292, in _eval_step
    p_ = self.model["discriminator"](y_)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/models/fastsvc.py", line 586, in forward
    outs += [f(x)]
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/models/fastsvc.py", line 494, in forward
    x = f(x)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 307, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 303, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([32, 512, 1, 63], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(512, 512, kernel_size=[1, 5], padding=[0, 2], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 2, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x55b58270f310
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 32, 512, 1, 63, 
    strideA = 32256, 63, 63, 1, 
output: TensorDescriptor 0x55b582c25090
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 32, 512, 1, 63, 
    strideA = 32256, 63, 63, 1, 
weight: FilterDescriptor 0x55b5822d4c90
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 512, 512, 1, 5, 
Pointer addresses: 
    input: 0x7f0250740000
    output: 0x7f024e340000
    weight: 0x7f0786e40000


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/bin/harana-train-fastsvc", line 33, in <module>
    sys.exit(load_entry_point('harana', 'console_scripts', 'harana-train-fastsvc')())
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/bin/train_fastsvc.py", line 816, in main
    trainer.save_checkpoint(
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/harana/bin/train_fastsvc.py", line 128, in save_checkpoint
    torch.save(state_dict, checkpoint_path)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/serialization.py", line 601, in _save
    storage = storage.cpu()
  File "/export/catch1/student-projects/darwin2223-voice-conversion/FastSVC/venv/lib/python3.8/site-packages/torch/storage.py", line 111, in cpu
    return torch._UntypedStorage(self.size()).copy_(self, False)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

[train]:   1%|          | 5000/600000 [24:55<49:26:46,  3.34it/s]
# Accounting: time=1501 threads=1
# Ended (code 1) at Wed 26 Apr 15:28:28 BST 2023, elapsed time 1501 seconds
```

Thank you

**Comment by lesterphillip** [comment]
Hi, I think this is an environment issue (PyTorch and CUDA version). For your reference, I'm using PyTorch 1.8.0 and cuda 11.1 (but it still depends on your GPU I think?), so you can try reinstalling PyTorch to resolve this. Since the issue seems to be from the evaluation script, you can set `eval_interval_steps` to 1 or something small to debug faster.

I'd recommend that `eval_interval_steps` should always be smaller than `train_max_steps` since it's what helps you evaluate the network using the dev set.

If it doesn't work, maybe you can refer to the discussion here pytorch/pytorch#21819 since the issue can stem from multiple possibilities.
